apiVersion: projectcalico.org/v3
kind: HostEndpoint
metadata:
  name: hv01-eth0
  labels:
    type: production
spec:
  interfaceName: eth0
  node: hv01
  expectedIPs:
    - 10.10.1.4
  ports:
    - name: main-gateway
      port: 30097
      protocol: TCP