apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rabbitmq-system

resources:
  - namespace.yaml
  - helm-release.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: infrastructure
      app.kubernetes.io/component: messaging
