---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: htpasswd-mailing-secret
spec:
  encryptedData:
    auth: AgC8OTMFhQU3upnYU82jjmZonao6BhkPkovRsRBx/Iw9Hh+ZBAximTD1zensLoi/QWxHJkR6JnWphYM/eNRHukNNRPUCdFqtpaLGkPQdgJysSZhgm/zxOE0RxIyZZa4706RByblESz+b3U3m9hnjaJ2QFz+b61xkh+IbEyc1MmrCABdolTUTJY9FYTemTCKr2pldN3qqk5INz3w9cmHNXPhmNHN+qzjDxPuv6dV0K8la4spSL/DHjAhgW9rWwORsJ0LUH4LKuDibb2LVa+S7HRsGA5mZ6XRwWtDWT0piDE+HvxF+9bAHtiWCnuJYoBwwlt5twUtE9Ndc8T5LAMr3d75HJSUdK8DR08nsqevbf3OOEMEFc3QA7jL7pTkt3UPNmAEgF9t6p5RaQWiTMURxDEgX8212xlxEKtGTMMv0AJHHYdfPiyl9keTgMt8k4qwMNKbwyCpl2b9Jcqzcq8rq1j8FnrC4W6DL3c+0wrC+AZvYccrQ5hXPuXYkWlxpL1nkSDc6hLCKC6kgea/C4rbzmRD14K/EhHvJPngRBgTC8JyHIiAoUwLjra8seR8pV3WzSlfguFEWdLAqv1LC/AzYZr1B7EvM7Unrs5Np2O6WAiWdF1gbgSc7dZ2i+qLUlzE7kWVwYzhKXiJbA5b9MLlhBn9+HyzIKMF14M7IQbyzXQkorR4C5RqLoy6weMUCbrJKyjBLbbf25h4pp/uBz0fv+8LoTUEnic2HR8FgtjW4eaXQc6+LNgUY+/wZziHbnbwHUidi1Ssg4dz+ckvwfQhaDtyX
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: htpasswd-mailing-secret
