---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: htpasswd-kassa-secret
  namespace: main-gateway
spec:
  encryptedData:
    auth: AgAdb/6eX0TRAiIugTbpOHF5ty9E5rPe9bTIar/WxCc9Oa8Uthv5b7TB6XaENZnldQqmDcEIMkOR9M5ZcgcVGrz67WIiHlr+Px1LrQ9gwzcEpZ/98W/RPEHk30T6918u9WOJZ7QYVNSpHJdQ84EOotKKp0UeH0lYzsQ8OTElI2SP4kZSceOt/DJsFqXcwbxMnyiHPqoAFN/J2cNnHVJ9ih8qgiiExtfop26Ep8OhEpi+LtStD/7i6WelW8IQoU14j6vClmHwkQ7IhtYKSdB5lyS6y11cSo09NuAMhHru+Fb87VGFNf1n1WBabTLZixVPP+L4L9GSyNKZgouGJOpT52YG/niCv/JI/C7nJutTM9GqkhJ9pY881H2Hh5QbOH4EiHG5ysz1aMa9NaC5+rlT66k0UIDuTHijuBok14j2p4kMlUiqoOX6pkPg5AowopgZ6Vt81S2l4wyIOe0o0auOQ7TDfYzbj3/vh75camXo/l9Pk8WtoWF093pQmYzsQhD9GRwmWiMukf0ZMjULgTkkrLrCU3iBIqQuLsiDdwnKwM7QcSro3zsYMRKmu5qBVGoBCTY67M18A4f7zbCUsNrzPj8zQyM2vFEIQahrBCsnmXWmh3Hh/a6Bt+ZMouYy+8cOWqwlSylS6YN11ioXerLLJFZXfyjq1zpptk9u1+0BOC6BgUGrcWlr4Lj1Mw4hThUVucMHu/duhTefB97fvum+P2xpD85kw1xCQzjF6VngJMF4qzFOufvBWZ11MTIncXSRrPJFrXcNicLjJcI2PxI=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: htpasswd-kassa-secret
