apiVersion: kustomize.config.k8s.io/v1beta1
namespace: main-gateway

resources:
  - main-gateway-cert-sealedsecret.yaml
  - htpasswd-facturatie-sealedsecret.yaml
  - htpasswd-kassa-sealedsecret.yaml
  - htpasswd-mailing-sealedsecret.yaml