---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: controlroom-secret
spec:
  encryptedData:
    CONTROL_ROOM_PASS: AgBCUIBNiN+HLXDsaXENn64cEhgcmyyVrrQbIrMGY4/omFwr+phTrxkCwdZ0e6lzntnMX7CW8LH4BVvnoDf4GaMMgx2F/MobMEPePaYk28Lcg+CFVWOOwUxOpVmNA/04yCHmVLl1aefzMpZAPpVYsR/KuXQG7HvcRnaMdCrmRwn6ZUDvYishd1dB1Ako465TKQ1iiNinEXWMlrNoRWqQxRRP93RKffe8n5uC/DZw201ETLAGNJQIvLtPYR8MLpRZPWJie7y/0JsDromPKBYwtOFibhK0RUNJx7cQEKUjo690j73WMgE1K037Ec9aeZUdqEBCONyUZIB4BiZG08l24MKlWrgIILZ3FnOBKRoNw+1jdXRLmmO5BO9DpjqCN/umynTmHi4FOr3b7iD8oGbNHWD4QLjN4VEgwTjPBSceo0XDDvgCbxhQqND4xgzFFQZxp5TjGzUvyZirVw/QQn5F1/orlIBguDyAMIsKyOfp5AV6FkQ2dSTnapcnWu/Rocp5lK1OhW5B3Pq4dsMRkX4oKu5LDi44Ct/SDakSHNdOJWvwatCXaVy7TiDy2vN8Wf0Ggf4wxZJrPGAhGSsMwF/5DFTkj/4zb7qcdN6IVYtCyL9Onyok9NIDJH/OaErjkqh1HwmHe35xtE0RURV7AN6Q1IOoUyTsFcYsvbUz1o62A9yKriyM7srBnK+7/azIk9CvokBI0M4h+PbEIe/YIJEiL7zDJe5QvECmyP2DJJfWLYOn4sSmtoxVmHaplQk=
    CONTROL_ROOM_USER: AgBtnBlbGsRnOJgH+6K45724a0kcCWgh05jRxUr3HjE9XH0woK226J4bxLRu5Qn9CuGnSgpX3b8f2vFDmow2tN2qt2oNjAdHE2zvDlfCpiJRZJF8/3wMcFWGzVM65CPNfgvdCNQ0Qnq/sGrALvMibGa6ZtUXmqNS7dTordUOR2oqEycbaUzmpo5bMn3Dq9OpexFgxiZebARcBkXeAvPSM18h3vY1rJ9DcKzbvB36DO8AJ87LP+BbOy7nvM2NUMKBQqh+7DQdjQ0F3jYyjCzXfQ9HaLDn8nx8XSSQyHj894+PkNUPYB0Ny3u0Y02iqxlsG5GlDxnNGMvLm5zHgqJB6u1YcsHTuR7puxH4gC9Hsak6kACF5wTOwIEGv3peTzw5U2/gtcZArAchs9ka2SqwDnVy+TsZv4JKYW4NUWPz6T66gIUv+U4zM+qRjUZLh9L44cmWcPJ0Y25Mfl0kP0q3lsyuQgx0GjZBFvq2pO6D+16paciQiXdv4CT79DJU5dsTNPRXnwo+p7T0PFrQnlb8yjez+m2F1ZfbIgrMGLuDCeBVhIWN5NCp40cVsrlr7igy42a1PwtmiEo9mXbn6hUsHTESHto0gKI3Sr5MoAnIVHSRM0ltKDMvJcqpxCpqVEUKb59aCKOdJ5cFraEnOcIcy8+cn1KyPiOZoOSRuRwLrYM5ZxdhwfEgTzqx0yz7L/RWaAQK4K8EFTjrI3fM7CA=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: controlroom-secret
