---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: controlroom-secret
spec:
  encryptedData:
    CONTROL_ROOM_PASS: AgAkGzRekOy2rr9OJ2dnjUfLsjcNJyNLqvrVRRYWdZRfcvCoQ5J2dDIXvkYsPOyWua7ziORBawXzCmpWmxDi2Yz9iGk+6jHQWobfeoRekvOzwW1yYWaTFV6AVr9H51Xib1JyXiQw0CLQsR7rLxyx3+RiIFI4ch4P1JuFk0w7Urd9t9TSp6bozZtUKoamluZW+ukfb0aVFj+i5ldPkRKs+mL+JLacdkZCzuGn019t2Ic5y/+x6o6S8eKRyIxvnwgPFb5Ak5sOBkvXHhHWPthmolfkbCJuAy11Qbo8tCYxQmkycwqtER5ihocxT3aLLZ/A5KZveyW10A1kv80lQugdf3qgsZN9hD252UHKo5JFAkoVjg6VxTxmVnxY7AzuXBQ4zLE8usHFtPoDHoGrVtwt6MZHu5X+0+HxjndEV20M6mA5L/FSU7psQzxvuNb2V29RXQcmCOGGoMjgCP4WWqe2NCeQsG4/Ly2x2+Fb9uZchOLsAHOiKjLmXKTrqfpU/LyOJixrKbv4ZiA9B3HyJM1sXFlfRrsVxz9/vlMN8IusqwF1IR/IAdIykhfn6jME+BJLXSAW5jkEc+v7tixc8fefdklJXgwjSSoN+bewQmU5jn32sx/kcDnI0/iAEBE9B5BTHbS8mcypqp9dI6vvcmx4T7yh3I/CFeg6Yo5PnNFnZwEswh0VsTtFubEKlPyTF5s3J9uwDWvbsG66mpn9/w/plB7fDf/R9xOW0Dxce1hkgHv2sMmAlEVBLXgQ1Qk=
    CONTROL_ROOM_USER: AgAdZgnfP55oAnhU7krxOUWuvbRQxDd+WLjEzbNmob15l2xStuOfTn6X+u6MK3TK7UdWvs/gXw+I9LhjeE+5fuG7yUC2dLDyYpmhLhyn5qYwVmV1jDBkEaxleW0uLpPYLqCAnVFqrQ1fHPR7csul6a98XYO6wtbGJTi6Tazd1cCyaRT+sutlGexacIhdnwM/YNHTR4iJ+c2xIUrKsK8VOb2VGf63EkrUzFh2o9IsQVNcV9D3bYfvABLB2dVrCF5I+DQjqQGUbjKLf6pivBanjHlIpodKLm9T8xO/zlO0gpN+nJquQ46TqvnqcvzxMVhjBJYXkZkcs+aJtDbpio0JOs3cyhzuRL3rE1VGc1vpFLRJkSiHjB4r62MDFaS6hsUHuwiocCKmJK+tivbeKskborHwGcoHQMINhJpNds76oAkVetf1oc9zaMAf6ag5YcT3jpqssADIKpHgAFlHHRAFGjWgzAud9m5rcXvTJpFYZJ+muQL9I4yETjw8uv2qnf3CdgM/CIpoaLqE6d0/fQby04XrTws84jyMcj0qOyJnjCDzU5ug9/82Zcw4KqtXzBNQGmTWrNCYh1+ItjJxj1Ie98RP+wBMIoNaeMQ0rUQAzLSE3O0i6gsqNE8JchfmsMnWl3yLCAc04BPdseIAkETqXQNIaQ4EmYJCgJf/Fr6s/7cPpreNgZJ4Fq+XeWxGUfiqJVbIyjQetRNZc1AcWng=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: controlroom-secret
