---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: elasticsearch-file-realm
spec:
  encryptedData:
    users: AgAvGR8yL/wcOLRBWfrpRnsfBO1ViHS6iK7BTPFAnKdO+pGOJTai+ytDqCVXzDfXd0c0ITwKfuKbar8fGdd9I52aage21aOG+WH5Xh+H6D6KFC33dxO6fuTVneiTIZ1ogVh+KhzQpfA+X4/VnWhP0ZocybYscjc6OVYqIldVGeEgWWAYg5aMkpgPQTsTW9B7nCsEwVN4ETmEqbRU8NTMdFPIrS968/932c5Dc6qF/pKJDovIlB4hY13jrWRB9CQrAEH9lXTrnbsweWS+ws3kGIeulLwHZoALDL/jfUu+OuLqc933qfrm9QIfF+tU8IsZdrw+3CgpLsmU4wYo3tZvap2Nq4nSyoMD4guX8DIj7jbtJSm221o8bu/+BXpBM8thlDkRSjr0bMumkXipuMA7j3epquWBnmZLJqNdWrbJKBqx8S/HxcAWIkFUT6wqOUFPtRybcm47HXlCiF/qummRYvKZ/R7/qUtuPwdwmBLlxNAJH4dzx24Jp62m8PNJ9Ni6tdK6TdswWdPs0x3wf04YTQfPluhnAjS9GXh9PHdTAGalVR0L0iCH1r4q3pnvP9OCvX2Jbv3ljQgPgV+EEMp/GaqAgR4J93n1auC9XJLPoW9qFcbO+8NsMpgkgBdjpg/UuYPFTM7jdnD76FwbFbiw2R1N1mSedSjgCjkAEmXAzxOV9D1xFSnjO3e8acz3Tzyaa0uoGsHc/Blw1jnYASSZXPyj3xLolYC+V8/O5L6bGAwR8bwtRBvl7YpCkBgZoO7fpDMqVqyIGCqr/ZMCWja6pbVdGCGUNb4VMHK+Ojbth5bfVPbPqBW7NQ9Kyd1wcTckTL9e9gOz8uFp9NSPonRVqOMBRRlVMICFYso6/Gpr1pAonCwY281dbleRb+hAn6MNqukMdg==
    users_roles: AgBDbwixi8NUBZHSRE4/Vt5S+ZAJh50eilJNt1UgdyJ47h30KebcNdaCX0C4/YxUKeK5CgWHUwvTiyhOFl5xq1yFTozsMlguIw7PdTZ1aMWdj6ZEhmgVHoqU2rXOHlqfkS14t0Ut+W5XEmfAGkV7LtUfjRuXrDt0ZKz+aOYC+N3PHz+rDyeTIpTZaTq3FlzmtBCOo7rtYVvebNoHlhk0dQWfKOAhT/s3M8n2Znoyi635sdanvZP3STSMGuNlPRK3ZZHfG3XhSM8/UhHeqCi32DaAfn+0vMneP4zlGyI+Y15pQsdD4Dk9642SebsolKkE06z7BLsSIPRLY73J3lv087F+/Z4ZIsO5dYeNT2r1BHO7zWD9rQtYOVmXIOzTB0ZN3l/M0cGk2n3TL+Oh088ROxSTpGsOf93TjTCe1DWhWbXeQzOAGelY2+iNGfD/lCMtDLipiQqG/ZVdcBReOFFZCUXtqwb+guSQdCPnK3P8eVvoYkE+OG6RTmO8HRcTyQ1/mFyh/nxu3qACUz9mYTa86ZFXxwvVO+CeiFv5P0cB5s2J0S2iMSamURiyDHA42zFVBUeLpq+eRbxsc3YhmNphvkO45DhJznWVKPtJ3RaR3q5VcMz2QDfdBqUfTkIJyLLgQn7TMFTpGovs2+7HLEOyVxmWJNO9wH0PAc3eF6moX+wHB/EQVezWLgLszFA89N4+zzz1qN9mQVg2oR1xPBLRW70npuJ7dQamVcHzSnpx+kRt6rKX
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: elasticsearch-file-realm
