---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: elasticsearch-file-realm
spec:
  encryptedData:
    users: AgCVZvdnZcjLEXmVCw5GXkDlqjMv4pWrfP+fXebG0zVfQ8ZwsGxgC8Er9nQjGWqWv+M8y8EzC1XWikvXeOEMpdcfMyiaX7TBC0KjYxiCWdwv8Ub/tfC8PmufmiZFh8mL0tX2QMQbhwGMrtLs53eeUdcX25VJuBCZPxATroKqwz6gEJBT52mThDMW0rUK5RiU5aDWZ+mWphbvBiZgLjpu7+xLWmu4ygcAQccQ7S0HA7bbYbXAHvIq7N63LeupCqpvhgkAGgrSf0naalQ2teSvEGvtr9H1syQ3oT39g1YpAhqhn3+PmGfDrG/Rc6Y9vQBIzC7ZZIFXe4kPeB1+9VLJ2osLCFOfOnmPcniXiICUncaSGY9dL5mFuJlcKzadWPZxldUNaUYXJmIRAl2qRuOmfTAUPsPjM1mvoymY4EQFTYHQXrKCHk/K7qyqfNzclg0vwc5tPj8tdp2HMa/XABTorsfJrI6ybGkSM7SDxeb1gYdR3nyTKtI5xWYX2U9ixg2Dw72Dp1QhUuK964luxG0Cd4LGS6p0N4oJgT7MwLhX7zNhCc7rId7sU2nHvG5C8kqlADpPuX0X3MA5IrCM0fvCwGIJaADojoqIci/XDH5DwlxlV56IH2d4o8Us9qtCtACeTmurxubrBVlBfdtRqJ2JSl5oj4aprejKEgt+QX0LoIGOZXsQY3jHfzv2dl9sPY7HRWLLxlE9GhRlt/iynMF9U+cvbvr8D+ahHb8aS093SjHG7nf4d/dWZlFRZs8sDLgPxkDLffVirHOWa5Gru0lnNX+ngLaClkKkEa6aYH6GG1QtT/OFKJokcPyvJ7gS9K25P2sRBStMb210LPYuc3pdyHH0tZ6YeHtV86gKjWzO8RFnihH20YkRn2faSNZpZaPap/YvUA==
    users_roles: AgC53hdb9KklzMiTqx1oeOhb3R7nnSEggpFRYs1LaHtJoWUAxSElxOvNyoDbEUkXNg4xlQrrUN1Ux5Jarl4299FB41R5ky+asxl0ON5YMLMTTLhivwFoTBbP8oevkmE8A8A0HqUPYKCTlwD1WlmhwTombqRDpt/nI2a09uKJ2HfrnNgEX+e6WLjC0QFc+D1Nl/hqDjtaOr1ipvT+H4BSmNBlWpa4c/9WXq9zozi60FGrtrd6Dujhz3RJEsyiJZCNLvtaOJwTR12VYGpjATJk39D9KRUxl1z/E23o7Z81WeWAcwPovL1ZyrtdP2MLy8p4aUfrAwLNoxOkPvkVBnUw1HOUKSZTHYtXZLZlqauYgkYh1PTxaPlxDXbx9COnJ/2xd3G5K0n8UJU8hLPiy0IIKjBbD8TIWOcKb02Bn8m/Todr0StAAqp41EpCvQcwoyZP0+Upc07Z6zwwa2dayhiiBk/YB0Gwxwkj56K8JzMDerpOUIpGhjIlZXOejcm9k0haqdPH/Lu5Ix93cfAPGlkxHcOgfQsc7NyHpbZZ+FBtnN0cWpDNkJgTKwECyIncTPopHhhzZ/KgfXeKlrhapd+5/RyDK1bRySQenArt0F+M3V496BvvImRGUUmcfmShgTvbiPuY6hIJU37CJbIjKh88gkhDjpMp/DoEkFVMIfwfU0rKXO34KPZ2AWZ8vg5xLaUOaHK9eOF1Yfvx0WRgMhUvBQ3P2bvYmvPOKj3Dvmjjv05U18rv
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: elasticsearch-file-realm
