---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: elasticsearch-file-realm
spec:
  encryptedData:
    users: AgBQX+uRnDynV/Qq9GhvwnfUgqfvGO7dSA3lzZyPB6FafVLLW7AHtSq9nx6SyhMQvywZIxMoHe84bir9pK9348tIX9s3HNt5sdvbiJp+jvsPjkXdxVlH78k1YcqQb/PGDu4erjju1d2k2VzmIowYHljc+zhVt/vKtUrXI3MvTuliBDb8AAB3i5BS/jz73rpxCBGsFk5EWbGrcM+HTWuTz9exCXMiqGseJ+1TRdwlKkNDTQMeZGsAVpx/d2mtVu0LX1eC7UH8aym1bwNM+4Qr30y7GnWksc53cIBQKiv09qK2VUD93eid4d0ytajvF46+5ZzL7x6CcrjsAYyN5JsgccHzn3XycESWlwLN1wah0kPpid088nOvT31Z0UWqYCjik0q/K9JQZcPi/ZP6zRDjspQOswDAVLC85T1aFr+t5mFrHYKoVryuJIzBhFn+Wp5tGcOKYXK+RNX+uQ3Yuxrx88NWk5+7pV5f4nBevYbdLOePnAAhAiTD8i+lVSLcz92mh5ch0EecN2+ASYPJ0Sln05CgaHlbmX1rkHYPsH90cKE3rNPIUaEiHE/RDLMihKHY2zltkFENTi02DflAY8bcSbOyK3f12idWD/fAyRCefRZlQU8wiVHQNtX0vSIBw0tXMzLYtSTcojmdMDsXlvipAS5RzeMvN1uFrCXC6dYQ5jpdeek1VnKrFsied8Knhp58Dzq2A7uLVrvkemoT2dLOPXSNQ7mu+aCyh2cL2Ce7Sz3hd8ML1TE6L82iyBueIPsbRQuAh8ZIyfi2GiAHQ0aucI3q4oBhiFUe0mSEdrH2nv6rIBdTXjyOwXWRc+KDXjuAtzk+I5uNuZh6nyUzt1tDi/lsg3GMLxrJtKsZY9tdN++/gSFbxU7kYX0WWDzIOcuUsFXZIw==
    users_roles: AgAAyUg5iZLRqCBLigQeOpAN8e3Q5321o/H/ouv0ufCQC0nWWWUrNeAv3nXxPwKd9WRskltuMOwq5bYa6/mHqxOmp80HoK3pIRVzqMeKGG1mO1ZtHc8DtxhVKDOTegS2dvqTzKe5rpM+GFpGwlVRhJaxXSegXQ/i8+e8307AQZMhqGv+5lsAT4oV03PsBUkmgZFSTWFC9AlZgY5Q4okiwyd0+NvC+C4mUF+5MT/BWL6890+UbOE5maNJNf8w0hSJqXn6qyM/yRRLRZAtg3i+KdNs77zBaElB9zOptEaS9O9jqbiyku1OeGNleNa/TUoQqDtnqQk+rHRNTsVHsfEnS0MfBnXX2Gla1l1Gsz6NmmSzKL43z1XqjUetxXTPEfjelpUdsprkiC+SoJ2M4zO0+s9Vs8VDRcDCV/Dvv7hqpgsCwksWET/M/Bcuqd+1qBUTGLNjquj5PLAfSB/CdecFLdbH/dsp/CFxD0zvTMJWWcE130KbcUW8ffxxbTzV5XPvg9hhFtM2320OsmiX5JREW4/JKOOWz6oV5CAthOz3qcro2/GHY2i4pIJxUaTWlwxguquBN7nAhU3WTBC4m17kOfB2NtFCfQucp2aagvoeeH6WIK6FKkXFhyTyWQ3KVAn+cEkTzP6zfWNPHBZ/sWgJ7kuLxMherAOWuEscCmho5OTGXJiKaQxNfg8v8eX5JYUx4ZMqWsCImok8X6JgxhbUYtk5mxX19uelidlNnZPuAhfM5B7Q
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: elasticsearch-file-realm
