---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: htpasswd-kassa-secret
spec:
  encryptedData:
    auth: AgBc68iircDkR96Bz78A3XseTUa1sU2V4fjmKDaHdDmpIUm0Mfi3Ktjq6sIOYxF39BTdSgfQo2uGdvyhdRXRu3CpVpCmpALQlH+Irv/uHxzQoorb3dNx0QyTTowo3JAAnWe0TUL1MYKO6ZyecDfSkTo7ZSNFg4Z9HMkOgbICJ0aKJOrslOF3nbQfL41aMMlLxWxKXuKndqsAcern51WTqNHvBGREW+7T+YvYh544+nCJ6IoIxk/Vo9HnA9PT5D7yx8G4OFuX2hP71241gQbi5Z6lzlH4DGvPq17YsYyADZgKK90DTrculwsRDpaa3pCEXkHtwD6xZUqERDVDJlzp47WhKvqLs/qlnpc8SsDNU55qKMzfRwwMv/Zva4KeOkWgkw67oVkbWQaTeiNoi+Wba6bkT4WqIcNR1nv9AMmSe2syBlF2VUwvf9oqA+VL7gbBlZvEn+vx/qCfsQkZgopQ3ewSnUBvsAsXV1ZV5tmQKi6JQMQFhqBUVEzjhCm1DmPbpdseGpxIZMonr/RkVMbRkhdZHWyNcfjEpvY5dwWVzAReETqGRe8VuwA5KyTEeLnhbiPhC3fXCUnQmQ0e3o0xyD6OJqxT5a/BiUJjy09rb4Zljccn/oikjbsSkMVBFnJ/qN8UTUmFB0Ql/W19hSG1YHfMhLXJcEmC08Ha13BcTBRmbViDCKfb9B5Fvu+S3p8UxvCuZLrrr+EZHoXa/l8fRhoVA2TyJp4cCDBRguh2z7y/Aa6I06q6z/vRuqju/l6Z2c93zFSReNgnR2wM5+A=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: htpasswd-kassa-secret
