---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: htpasswd-mailing-secret
spec:
  encryptedData:
    auth: AgB8GRypOHx1v11LK0AdVE8twABHFD1sfsSUbDQhUNaNVrpRaX5uowV6fAqQhOcXUatSqmsdqSpBgcTnOYXwP35P2Run41VsiRB3XwUUEoXqXhBbyo4XoCkIi95mrWX/Ao/BK/6lFIDujp4b4NIC85HnIA9TqMicwyJ10ayMe09qUdbzdCseXJN2LXttXg42712bJvyFzoSlXbg4/xHbWQ3WRr3WvUOmTy/GUO4D0VfIw2hedc6dD15b/Eoh9qqjddWDlKoR/x32ESw0IES+j2gkmCe6ifXIrS00nWzirb76g2+CflnuMs5QfpQYAPf6CPGvLezlG59qHLydD4fA3oDvtgRQx67V2J0iiYpNDGvo2t2df1QzbDdxA4UBQ7Qd1sGVztKED6ukRkF8QS5Fg2bPBBWNAwmtJLVC9s8x2FNYnFYyOZvZaI513DWzhrPUokXnY/XEnGhfagoi2ZKrZOG1Go2X5YaLXf7x5/ABwDehjGvrUEDsw3rIJSMzJJ/yLO3HNQrc3dtHbaCxZH7J8RXhDu9//xAV7IWNuvGXcjIGB7/b1fc/Mx7yE5yd3bip7H86ilaDZrc2R6Dck0kHLX2eZY9S00lkPwfnvqasPYrk5drnY4YJoIw47WKu+pf3E/Hj8gU9ALcd7nQR8M3qXW6IlcA6scNaElBHMz6jabHpnje8O4g8bEAowfSYvoOizFwDaZf4R/UOCmOAuc9uMOOHasn+VL3GNvAWYrDA+chXzQaDdVRcWYAR2YvXbb/lFMONZW5yV8LdLoCZ04xfom3i
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: htpasswd-mailing-secret
