---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: htpasswd-kassa-secret
spec:
  encryptedData:
    auth: AgA/SxVVZ/A12BO7tmtyYG2tDSfNvXHFpyBqo6rTvlpL8T2i4R+p2hz/Z/8RYiKSN+/nDJByfGguNkg8BC0aPxCbuZBK297QfshkJCNUTLeRWYCas1ZiRi6MGGkhyei8WHHY43ucc5UUocf+xHalEQFInkm1tWy+70B2Dj6uY9zVCA9dixqQpl8socAquurlssXrfYUpBMtxQ8k9e8K2GDGUS8egVa22+T1Ro53PLx8OCEu8TqWlsyXuirFxtRjsep5QQkkm3Tpks5xiLQ/Szxu+pBZR+2aXx/7VbjDDthpZcUf7Rbsm7N7be12ptT60At1iKFFkXy1N928M8pNYjd2VDqO8pt3G3vnc5lfSGPSxWNMcddP4LoymCpsJY/v1x0neccXr1vesE9ypm5k5NXypoYk5d7ozYPL3l29TwiQ5cjT6a4vAw2UEQ5veVG5uzElBKETeF4r+yCP5927nj0UtTTA3EyYs6AoK/vi1vaCC6xCsq98YP3nx6LHXSmDRpjKKsVIEYqsPho6fIrpl8MKVoUVjyPyCbKOZ3G1VMwj2LOg2XLGd6xmU5Vz1WRkEqhvVfbkXz+9jZWo+M5Aiw/gV4VrRjonOXuGSNHU+NyVCUh9Nx1eqG7r6rRpaNwExYls/mkYZ5Y+ZwFqsLNA6f4dRYIaaifGPUBhQ22H/UyJZGkme7KtNvaaW/MFe1Aif8WnMUuj16WSbFJW5VX40y3P3nEfySbOQGRnRM566H3OjE0Y2nhpmBk+B/a7FWhiD91eYLRBWH9XLgcP5O4g=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: htpasswd-kassa-secret
