---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: htpasswd-facturatie-secret
spec:
  encryptedData:
    auth: AgAYvX37EsCcQBakvltSJiBeolW9KGVOg1O0bZo+ldO/FZXBaCgAYHZz45Lli37HEsJsf5c94m8P73KfM/4SnOEqyZyqGkQMMaPMGR753BF7vymUTtat30lWchTHzt3kgxSIgcyQAudaT7vcVyhZvp1FPYAHuW2sisSwMC2QrJJl5jRUuV1LoJyexCEX2kauOYKRLI2nDOc0IPmjv9ithe1DFxr7w9bEwZVmYixBagIFfVK7g0RzA2cRzDuB3cICkI7KGz9NSwXYpWx6PD/FVzAz8YpHFtO4Xw2z25QLprBGta09MaritShU5n2CZ2UyagpJHdTuU+1F4ECC84EoUt3T5vzx4TkaK0es+uuJaZ051NDfxuwhITbc35t/rg5svpAZMFkEHt+MMrlz1kHPSP95e/GUClehLci9oHVpv0EgwihQUomLMuq7GHMkXHPP8bbCJrc1Peo8Li2Az67L7NHB72zyHmCQcSE39L1t0YpAkHlF3gHkXiy5DAvJZC0SCo7cnosaexxnRTLGWj6AIjNqhIP3aHO4l27aVi+NqENpUF0r+mNZaS2hbumdK3SN53D+Zr/I/qBlEaF5j/syEX5ALyjCXAIVaVNv9VpCKSDUDjXybo/22ddS9sa84fXDZde512yoyROLfnYDHQ06csx6TBOuosUV1sm0FQmLArTDflCzqsYcaZIV4/EMtylDsx34HNOo8LZanJabI4mdYb2nwu0M5qHuJIaBLLUbdywqfZHlnuk0FBr5RLCsNweW9KIx3UPnUBex3bw/0MqGXjTS
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: htpasswd-facturatie-secret
