---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: htpasswd-mailing-secret
spec:
  encryptedData:
    auth: AgCJoin4BZ7eLFlVzrd9wI6q05tuKbF4r/FFtGe7uLaprBPC4AHtuP2hjnLSUvbMVt26nFurpKATkzow50P4QIBMAbv25uJVCTAItxiHACxJqi6McWmU6FLby4As6dtiDH2JyHlKZ+ihA9wPq4Hx9Xt79Q8WcVcr1UvDmZBk93umZTcauD3oir4fmKpPSPqYG29QTHw4aOMmBDazsxL5fGJ4gbtyM01iLQmfPWTiC2uhIBpfgAKJMDPj1aM/P5knBtpiZLnzIKfBZj7QLOPYFwu3xXxvwwPJHc7a/HuXWOCnHV4pcoDcYiusb01CNDqrjd/qR9ZZWWEfgWMrWNZMhI70Qq0LhB7vDH2EJ4itb7L45YeExha5BP3wxTHF6B2Q6EvZ8NM6yWNa7HkMYUYpbj0Md3gkpqEowWlKLY6FJ7C3o3/EbClf53oRSeufL97cxnpvAdY1DhRVR1A61OclVmxNY9itlkhYe+kS13Yi5dBgSjx2IJq+PEDdUhMSFoQ2TRGdMfydYG1sDzA9iYuvrw+gsFayy/Hwzf86cbpmyYF1sWRVSeFcjCIQqmZJqyfFAkTeIow04xZCgHhTr4qTPoZMCWlBN1fOpJiXzqL7kFHt2crsB1Mo2ma8ZlnYR7xlzsMJ0592qkpDNW6CWgHoaFMokMQiaN0jSRbrf9y0+caE4msJpwkJ+m9D2kcV6nLL507s/ceIuxrj1kaOC8sTXpwSTEAnJ4t9JdOYn+qlZEP5uo+04MhKdDn91ZAzp1k=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: htpasswd-mailing-secret
    type: Opaque
