---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: htpasswd-facturatie-secret
spec:
  encryptedData:
    auth: AgCKavQUq3eHCobHCM3AkHBhwYKhSMGh5BkMZ1qqX+B3Orjp1uDUyvTENX/C9x9AJMqzlItZRs21Bcljnu2ZSejABBq/p4UZtrfHXenufsoxolULxXHmAHcQxD2bQMDmcyMg2AYNsbjONwF7aVWIhP2JFFM+JK1wgLCVF0HgTkTjMvyoCgglWdF3/ANlygc+a9w8W5bIFu8PoeVSzoNAU7ms9IoB6WStVWjKYIEdpRU6i8YQe+cCpZdREeS/bL8835ypQ70dRPG1RU7ShvbFtHend+MtOXIYp+V3yaKL4/vjZoOssjed2kAQJTKWAqFOHMlQTs6D7/GbZBHbBrr0nQlxI+4mnH9OEUggv2JFJRPPKXYztmdS6VQdndUa1vvWE8fe39/fwqXYw01A5BqA82vqPveJofLfbEsCMHXyivxTNMLp4F5pYZ4lLZPn7h1UHaojwIz4HwdBgaKiE5htLx5aLCksyouPn3tkYU6VHQsIB2+rSlL5c4gynn/LXw0EgPvmoVPRzsv7FrOZTEprcD7ztaZ3HyEX6yotzGN38jvrGY0ICoBQ5UijiChO9sTfK+OSicAAvs5/owPr7M3K5LadIbm8GSF4dqjGo7TzdcM257KUQmIShkyeWqzS2cVj9pzfVdb1YZNoNmTU5ctHzPCvu8LUzswH7J4/rIsJoMuLw6crkIXkhq8vk0uI/3WhCfmGIv+GNNbqVK7J3PIfG0Ihgm+H8rHvQVYhrL7LgTFGhN5RUSBWgD2WXeVuoQE8fWvYJ+5U9cot1dxzWFJKzehs
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: htpasswd-facturatie-secret
