---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: htpasswd-kassa-secret
spec:
  encryptedData:
    auth: AgCc1XQDzlpaAhpYbuIFo9fo30+pNqd1vg9udGHbBmoadxhJFhpEkwoO1h0G7l5D8f77MGOusYi69rk7fuI/5zgrZBqHRTQEtQiV5Kt6a6RN2i3CnCUlSE3fPBFBLQwJzKkg4jv3YOeFoMMR8qrGt+jDfk7plUwRa3O8O1wzUBjdDdaa+4ckPVFXm6Gy+5kt/DXG73B+jtmy8ij9SLr3XjkBkhxYP9yZdtj1J7i5+pyF9vLDZMX29Qo6cYldfRZPF2BarD5Sw6cJCg8CksTvXu4S9/DHj86kJi0YmrfgbhHQ1O2D3prDurVS1LZVhlcY9HEyBOJvKLdRjm1gR5v3+UP71tWOlk491ophitetWE8if0tl62YhaaDAvwnJqxoeGlMe+T2U26dJXSUhOkSQih5QTg5TcVYemSd4iwhPn8xOva13kvP59T2yN/3pmVyMBqPyGzG5AzmeeD/y7YyRx69mgk19tp4AMUoyqu+BbcB4RjVc7AcUdLB7cG7MdEyqTSF/HEBTzlVrJoLn0C8+pc498+1AzqSpVBWSNbPK+cuvv0rTmqKyZOJfMC82ZmLKJQrDG/QbD2LXLY+BBY6H/mcTI7GI0sW/N8SqtKLJZbKe8Vxttf6FV5pJibeXmw7eWe0J8wC5cH0M7kWSaxJnmYtu4uznB7VbRLoxBe3yxb0f0zqsQjvhNwRxDE/8oG93F3wStGV2Nb+1S9bubo7dabhZmSJ4f2GIP7m3aaTYjn4rkFbRQBEe7ou+E0QXNs274ZAQ5pE+OU4DZb7CZF4=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: htpasswd-kassa-secret
