---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: htpasswd-mailing-secret
spec:
  encryptedData:
    auth: AgA/kNrHgz+DAmVQmReP4LtR0lbnaHoUTebiWL45pghW8NMFJgkggzN9p9qLNM0ejcTJSE8FUIm+yJjiLtv9huKc79IccMsswt1jE/01DkHNKsfeZok7Qhk/InnbrMQcxAvQChD79KpBa3iBxJ8Cd/cun/TwTDGnrezzTTq5fXitJYSHPsHVoPkCW6WjeyranclfE2ZM7G1oXKDPMmWlXqbhrgQtFYti/TjgxsifwzM4m6d7g2oCPVoqwXe8Fwzam6G3FrQ0IYINKWJKWdBMdwOj/UZjKWFRd1xIjtr8tDn7qGwRGc9nptNt2zi/mHNw0eyQGH1UYGpUKzT+x3AY/LSqbSjxUtb80n85CwMxjqVnERKU62nAmslZm4ONgXaGkgW4LfRotl6qUEyYw9EXRkdxik9LR0NyfbMZxlMj8eT2ZC7txPZ3TyeRiBHWCgUiChcz0mm2p1KXMelBk5ZO3Ducr3IwuLOZxy9BsYQ+1UGnqa+i0Y7aKB/pKV4LSkSFKT9IuUDLjGrA1/pVcMg5fObiF3o9MacX8Z9IcoD/BHou+RPDsd8WFFvt1Pvm164Ho66R0KKhsCU3mTjhbHiRFbi1pTrQJ/gV+f3OHcpiH2YB/UgKncWF6C4So+BMaLSx9LbI6On0AYv+bcX3isPkYA59iAaq6xWJqAi7EfVkAZ0FNH/x8ppNXxBgrRqmU2Dj9wy61OHKzx+oUkLMODTmCQBHKjpynf5Y9k+YOz8Cq8LH5wrkTLOIcaUM+4QRZs+MLpuMMhTTJQmWUtamAWTR3czQ
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: htpasswd-mailing-secret
