---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: htpasswd-facturatie-secret
spec:
  encryptedData:
    auth: AgBsRaDB5yA4LU/ZFVSOhFAWsZhLjANnjETpVVLBPRjCAc9XhM1IjkYQ1mQ2eEKqYav6SjmW9Q/YFlEM9aSm6sKOflnhZcDpd4euUj82dYb4w7wlLXcJmLE52Oxfahszdc9rJCww/lT5Q/kx7kJCfyLXcF+M0lJyP2bd4UNtFLewCiyt7wxbHQUL02lAWn8lzF1Asnh04YL1HDsqwc7Uw/yLrYbsp4zIOT0qqMz7leqN4PS4GRIhg/zEJSorCCe5MSoL9waLEyZs0yhcqkIeGmbXOqLzDYkooPOm9aYcuM83ciw23jbzXAKlm0c26DuiORUYDaIyMOxI2Ms5cSuwPrDW6x8lvAP8qMVRuH2OzRc6S3fR/A5bd8fkKaOA6yRxTwbl3DrPqGHt+dk+2mu8TArSKoDIBQVjj4reVfriA0dmtg4TEsaPd+l+VLHr2OqyThlNYKwgCqTUai5hfQyjs/pHCj730TX2c0wo0o6dAPCt49LLzgbvwOsW+Q2Wre0K1sFNPA2KvMa0Ean4ZDclLgNHiDIGqtCXSz2uAXD5DXnA3YyC0IEqE0Qwrb4G54PFqXoh4PWamRoevALZCEv+Hz9BTxH7wr16BXg8LR1EXPpu6tqqUOM6agRMDnWehCZNMSkL9Z6XCRBcePf0ZfCsUjCxp8ZzcnYC2sekLBgNuilLJvG/ibLrzOvTraStR24lnQWAaubY2ug37zP5jsKbIrdoyISs1nrW0AplIR7wNcZFJIRgrmQ98axqAcRPqWmzJ+JLZuWZ/wxwALXu1rjPUkjp
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: htpasswd-facturatie-secret
