---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: ingress-secret
spec:
  encryptedData:
    AUTH_PASSWORD: AgBiR2AqdgW872Uvog/oB9dW7ZJRmf1jBvDJ40wCfmIwD0dUmyotivkOJdmyx1VIwrq66yAGxcR2avCyVR5bf6CWR8SQKrd3Oz8SjXRdc51s3a0HnyNP1TPjnwsHval7nbv+s2J9IP2RCQsm8yBlgatthpi03MdyOaEyTLtPVThTKi5ITk+12h8wMR2yt17Hr+gkNvg7FT9RY42nPTWvzlAKWXDgJ5AD+MLBrcssWeBLSG8RlPaGgGUlSVCo69KkMTcgl5T9XSr9AWJ1ty8DqPjhGD3zpZkw2ZBIyg6iT7zDfswQL3vXh8Bckf81IN+nL0/ZiJFVNbPkCB0ukJgzkVocqfUspZm47bta6tjBAtS+fukEMcraxFjGbbyTVvSm5NPK7sX/1uRUpYJCk6ranSWaFv5M6dmzV6St8h1p9Rgsq2lghjnOI9Z43E1C70Mzn9yP0+BDIllKbHzP4cSaIsEaIB2wdwecMQjm+iq3G119gXh4yN2O2uLJZftETIQ42h7+9h+n964MtnAPq2eHo8BFaiVi96L9HqZ7TULWQqJ2h4vYGwoxAeCbG5nQnVdxJhGxHu+slaLsN0nn+wBArTBOzrEWZAWAO425gIU8KkucLgyWyeSdrj5LHLDMPVWHSXOv9jm5m2VKyBq2MFbiZ+OLVp3F8FgpFbG8yo9+mRzkalyQHRpUHYDif8jwSnQZR1Y50R0s/A==
    AUTH_USERNAME: AgA6b4IKMGrxCN9JeW1iNtsc+VSsqar1FZcWOlDucWd/pts55VVs351EnXuUNIK2IJc3zes8guUrUZYtFAkLjtOGbOmjPRSo9tIODrWp/JgQgfa+UXjIX1UFHKz8Fn2NAGqAmAd0hLfB2AfVXktCSYx8Zp+PnM3YA6/y1I1aT671wvcZ+vLX+y1U5ZKdiAmBZmgV4MzyaUy6S2HI5i9j0CVLn0WP1NeaJCLTo+TGD9ayDN0wc9/qn0vwev74ELbE2T7WIM/Zc/cKXk6hFinQBwNQaksp9CyvLr/f/sg1SmtkuVLSZbrsJYibvSTlGKrzg1xSyv8M7qvkIJ3jmVGTGin4CfiKdt8UOwmkkScXJag6jLO1vCgc+AJAd9kcHCLT0s0jm0KX5GBIpG3Gj1j1+Mk4d5Hs2lcTR/iGbFX5hnk+SwhG45SvVUY9aWmKwkXx+wF+LA7VEpXKCOPoiU2WJVTBLaBNsI6ZMHncbVD0nYPFaXbfW3TqSvjZ9QSxfc2E1Fcz0ahW28xI+SzwuTYrC/tIGbAZpJHtAD+QUKgTVE9l+IBl0Ew2+2Y69hv+kh8NeuQVj4kHko3BM0+VEePfn5lXtYc9brQOS0DoTeb0JW47bJHfKn90s1Auo6sYfqkDEPCUkqmcLeQyWUCiZbMBULl+ByBB7Z1Y6jQvnG+CmlZdl0NHWpLTI0UwTzazumQC2WzsKct79A==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: ingress-secret
