---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: kibana-system-basic-auth
spec:
  encryptedData:
    password: AgB0Y9nE6Vstjycp7fLuKLFxQEdEHAd+GlVwQVxFJQ8Tn0JLjF8mIzrEojbm+LK6k/7wuhbPqiPnjxixnGp5A3Iaoh57/PEhux1Dp6h76F5ceviN9FNxtxRc4rTHxdUg7bMayvgnMeaGfqigygzbD8PIaGyubW/KO8GfxU4lwR60riUHQAyjikPW5QjfirJPZZgu/8lWIdYbhhnyH+a17WMEP4usz4Q9N2KINXzqgBFKZjcCAt9ARASevBr2O4umuscirhJj1imII+7v7b4Evy/tjK16N8ifPrjb1eo98ndh3WW5Lwq033km+Z3sQI6W3EXmNoSIhKOrhOyzK8BNT3hlGl/VI+Cf8Epf29llKPimfApl3UQvm+qSN2wAUvXxJRUah9NjN/sed2yL1MtW9uzi0FkCj2IJ6skUIE/ypQbNLG1N8itEEjRcU+J/TXNf4rH2NJo4L02MHTafyU/+xMAEmpOOGJy+yqs3VZT8PMndIuNJ0nuM191eJFdBDfiKWQ42Tnbe+xr/6F1TBfd6phHQWb68Msa+oAx8CNJzZcacly4qtApbIeNI7bWMr4XxS/kdL9dBZowwKpmSI9PHKKM5UHg0URlbI/dTNGcyRCaV0CC8GWCphXP/tAYro+Kvq88oCkN2neyalVRfZ5flySy3M9Uasrj2A+0+SxEWWLpuJnXJTRPyj8NQNn80F2OQjUe1HT0+S2yi8HSYx+svtd3IIDrX9MVJjvBCXS4d4mq8TJOkHYCl3ST03F0=
    username: AgBaQ5W26UcanBXPHQ3lsd1lcZVHV0djydpYexGwoG0ka1YGjxfeqJgFVsUK87bpVDzY8b7tXVjp/kXUkTQdvxWh9ovqJJH583Iq/LffThMqiiUG6A+9zT2kEyNrniDXxpa7Ji2wSlNJE4AaJXEzckMaScjOtKdBZwqqjzIYmdhafDt2LYPwo4NqFY6SmG2zLkHbImnK5BBcK1zXRVaLJvJethXO7DYvF/xVgMKLGlPcs7ShM6DSZAfKnUGzvMvLyEhZyRUuNPlGt+yJKNdbSxgennY293SAstc6HW59cSnpBKtq9x0OoSnfP/HFpZbDSE4+WjBTvCRwFXUUCbokFatDQ/HH0TJ5BAEsaRisZjwmPn+pJ/+WmjmnTvsV0BXVgC8Wpo3cDqiJykM0M2scLjPmWi5kEv/D2MKIzuZO1g1YXPBq1gF7DxI4dw5XyG7bHC5ZOBfgssJIpPP+jX/nk3CHlFpas5pJLGzYyasRFdecKICIpIwjafAwqE1SMyS6KXlR1FM/K2QspPwUBwCUEYgtdwzTcrICvH6aLRITd9bsNEOD2JSDI/vIG4HcjCeJdibgD4QRjdluJO4SlCT1NOVnSwSojpugYw9hpH9ZOlCdzv96QU7qKD4DquvAvlbeKkPYSFOjwZUBquzLbuAE7D/OfGzLETEgPIkbDoAy0arY1Dw3+hQaOwX87uLRqUBMlpdf2FZco+RxITtPe5I7
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: kibana-system-basic-auth
    type: kubernetes.io/basic-auth
