---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: kibana-system-basic-auth
spec:
  encryptedData:
    password: AgAzjFk9F5Rt3l69boD+NZvhzVuGUojHkk/kwmf3tsb57cHxfBF2hltE5YngI6+T2GVfG/xYDJg7lI0M9Yk9lwpMZ8Mb9+RvkCcz3qsoG39Pj4F9K/Zbre9UoYR46Fr4J/vv787DPqrEtGSgg6XzV158PL68BWnIwmZnBxrngd5WN3aeP73ZdjcSsJBLPg3YgrZEBb778oDfhwZlX3bYxOwoDA3upxu/IcEQ0CHEWxCL3rdcN1RRsM7pYIMTdrl/m5uvZ5J9pZ7rj+fCgLtcmSdNuurUOl9tPJ2msP07nDf6CWEXtKZ1kXcZx1mOHpF3CeePZVIOcMK/eD+93qhoHRLsL2Q896ca45pe1meeTpgSlStmIuaEHBt0CHfPXtmII4lqqE7aGAX93DRbSDlakoaRVjnHH60p+Oo3Yg84TQpCpZiX7rAwcQZo58PitQW5mqGSC47XjMxzScF1OAsXzIinbpxRlbmAWqh5kH1teOU4Xl+vGBzTj9lEuNEFLreo5LJCxA7KZTCKo/H5IM6VUhqd9yDa6D8+SJ2bTHPvvP59ev+Y0DcWuNZZz0hDg1ypJQ1gVRFA+2t/UtEFIgDBwXt7dtKfM1xMDFWMKyldOt9MbICYxK06JgN/HL3lY99zB//7oGk1RpwDynyjsut9KgE2/MXBM2mxosBIeCixxdEyIVGHM6J2FR04Qj9/nFH93CdYNsoC8/sdah4QsHsWl77lPMfO6mjrMDh8b6/SlskzHKpxK3AhsK7plQY=
    username: AgB/8uGtBiijbuCvuEkkuXNhLf0NEQp3kPAUsYkWJvgtec/c3rB8sH51Cy8QGMukzAZFh+09Ds14hr1/TaLc40eilTaMWSOO5ts+b41dLEiArIusTdI0wzO4MPSKaNyoRQsXe25TxnWlGKJZyCsZbwEDTlk+YqjVxpsCgp3mFKSaYEzlYFSd1Fk2KZ67u+4DPKxX7Ltc2mUW9Ko6WQinBYN+zYFPIVBtRrzGsmGQNVslleFV2gC+jK7d+rH2tS0JF/6jEXhp3DSXoPR1C1O3luUB0vD5EFeVcFlVIzPRbifBkeLtax+RtdupOrf6QWWMxGHpAM6uOlDtcueFlFjd7/eg3M1kD9sIJEFy5iw5PmV7NSDWlSUsQmoQ+Ml1EiP8P8ZXn5//qgSNMFBvdO/o+ER5KGfpJT7Z23IoValkbRBK/kOX/ldCLTmK4fnMToGuT4LXKwYBOURUTpfIiFzwy6t6xJlKDtQ2P+nBurmXNg62d26+YtiX4X9sJNKmdBTUhf129QHVd++R8nIr2Kyc5BCW1EEs/now+h3FJfBupibMYFoBXvn3GaVI0JlTgmB1udmaVeJgdr5j10XXLqCjBsZ/FLcrVD5y11jbCDsgKj3LYBl4x5mP9mvIZSnEjfKZaqUqsdbSQKLI7awVVrmnIDnljvHqmZm2TTDCeAR7PsRBTIwuLYHCKrulV+MrcdjcRxezp6X5X7zC0z+nC3CB
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: kibana-system-basic-auth
    type: kubernetes.io/basic-auth
