---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: kibana-system-basic-auth
spec:
  encryptedData:
    password: AgBpkQixA7zvE8ODDuHpK6AEXwbxbq7YhxP+EygGPVIzoBE7oKQTvi49220KipMhLgSB0v43001COauUvzQ+tmMw38sjRyjrMNoXtgTMmchIsNU4utvmpV1NhAEizdEtbRVksUtPGsIW26mLuWw2atl/LGHh6gOqYW4ZPkJat8cgTGVHXM5bgJzDmzI9jUusAARlRj3TGehWRHyl0YWD3jGQ6l5xeGTF39Cu+VQOZ5B1vpZBNmr+3OSo3hoQHI3k03X8ZSQcU3rOwTt4HJ37COUX1a0LPplVW1Ka86+mCWmoSc1cIzx6wmj6tYcjObMcKPpdv7MQTdZzPI7lD0bt4z8gX3/1ygatfXLykgzLR0MuxhMzER5zD8kqzLNmuT4p/4QhUGQdbf8Os8RY623ggMgCAknmY1RBgpR+LL+RyV4w8CAJkdwq80cLAyTVMWUfYQYLsSY+agSQ5P0Lnv4HlT41w21b9QMKPcZSAFXkkljKK6Cc1NVdEzNGSgfQ+km5huKUcu/XPBAVACVpQa2ZAhz2xvKxhUHr4ct90UUn+64zm5DaIWMMpslAmZNdrMUbD4xLZgG11A8CrYt7+i3H4f+LN6V/KZsFCgMTZa/cfRRmAKLkKgnC6wIhbCzd7uhKomlnw19GMzHX9RRaoruUQQPuB+O13LQf1fxlSw//vNMzthiVohkPRZ4B8AO92N/a+9jphodrrTBJScQ1wloNFnUZEs8UyUxZBbWEETBrqTrlearkMDKnimSOyIVe
    username: AgBoT4Nerqjp2CptlbhHaY6bFb0eUpJeQK2je7XLybXLEQ51rGwUPeof9UESeBM2Gsd1Hk7W5GR1DxKVrha8brguDtVNUgiJm/77myMH7BWnedvcWRA9ECVzZiuFE+zfYwpvZQu3x5jJXTcIL+jFPVjkHMp2Fn8ERpSSLb96KGgjuCuab4myxdNqmYsWlUCUJ3LqJjkkuI7yxNbUibNLOxlj3tRmqpFQl9Y1Kw+YmdeCQSWMa0GV5zHiZoeTHxsrqJP1Qz6UlXLTl88KiLII5sCpG/26p+FBqeDg9PrVedpowANe3ROItVblf2zewFz58OMm6Wk2FwpAIpHaIYCRIltNxB7cnkJZvxw8z1giaMbSkutl9tOYGn9BH1/9A34rP/2cE0nmnFBgVA5n1KTdJyM7z+f0NGGMtXmHaJ/QuiBEy93yf1p+87QcFDtyLmahHssZ2E7AxnsDJAE5qruH5bzshnwl/JerjIeCn2UKtAkGJcAdpU+/O0STIB5ea0kHpKDepl8ejMPYxC01QywxI4qej9Gntdo5PkvMCvpyrOmwNAn0jo+O6cchiUJgWvcwMXVF2pnMYRE5mtknZesAU6+Edg2Qn+DukbtZG6t+POXXhsIe5smLlPm9Y0CCyFMCkWuwCpVObw3MKEJoXTUk1XkFYgEhruhDwujT2hLCqs2u1ClvPp4Gbxq6nANGOapnkcDj7pFlSSC5EB+v2Ff4ng==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: kibana-system-basic-auth
    type: kubernetes.io/basic-auth
