apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - facturatie-sealedsecret.yaml
  - controlroom-sealedsecret.yaml
  - crm-sealedsecret.yaml
  - elasticsearch-sealedsecret.yaml
  - elasticsearch-file-realm-sealedsecret.yaml
  - frontend-sealedsecret.yaml
  - kassa-sealedsecret.yaml
  - mailing-sealedsecret.yaml
  - planning-sealedsecret.yaml
  - rabbitmq-sealedsecret.yaml
  # - rabbitmq-default-user-sealedsecret.yaml
  - mcp-master-sealedsecret.yaml
