---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: rabbitmq-default-user
spec:
  encryptedData:
    password: AgCqqyugBFCakl8WFKzgY1b9VlUQ2kVUZSm+erSdA++y3BeaxA/mnFnmOwboxAG4iYMTOkwh0C3YWW+ebyvs6tuwbiYW9w89iCNfyp2+Yfq8MGBtZxpAMHHdEhYuJmyowWF9NmCC7GsMdsmKrKn9eEmbq6HzLTIfCZmW3WDPdjdUk9GWC3n361uiUEMghe8ZQzyRPIZrXaUuIDNBrgurVP5SyMXkiVzgmEbyDbYFbCEIoiEbggJqrVCXwlFat0a6Fb/7ZIdvIH10ywcH1W4i85L2DtOw6PBYsGM9BT2ZAhoUzUdOrmw1yU+z3i7DOmXeHUr7roYLujpD+eDCs9qeov+fGx7dJ7cRrbpxtB0j+BHzUbDyi3aiJEdJEb2P+nAhFRgIiYHHuLE4ZnSFZDmK9qOBSFZZpw4p9jLDYovfcwbbev0BCZklIPdwDB9/Mn0ccWFyQ5czzdRcZz4Ry+v3YG3RhbiH+hUsv4ny43XlmHgioi33JuK1+1K/NurYMee5GWNtR8+2b2pe2lD1TbO6qNnd5jdEBT+TJm2DYTH65fXEZdVKjTNnraWwTcD/oQuy365W3nFxkCIAxhhKJNXIkGo2RlNOkfj3jOiMJG7YMPdXBHEWSJdsOgYWMjSaIeSuUgtNRJhziEbqwmm3MlkAE+pt2196rzcXZqdwjk9jTD2D/CnJB4sUYR+UwDjQkfXNSU/utXkK26tHU4htGTOWse2+vsAB8Ny6dpfY7up06aVFAhL7OiIkhsq/Oi3WzdJiuUdNTg==
    username: AgCNorHOIgIvvickubmbRkiDVlDoCMVmWorJu0dAgiUKieOg3jW2fryHr3kZuimxXBVLor0m/0UTu/6QwjW/AHTriF4NXpv4l6ZiW0x8yQ7nf7g93LiyNNcOnY1xUcGteZnc9f2NJRWQuhG27kxMo+wGckl4w8/mWQGDTYQj+bUkaPuN6y8fq8GUWea/wEFjP9uvBzD+RGw26wfjS8oKhPLzFm2h/0Gom90ITBZWMseMsKHqXMnFdydRZma59fHVMvoOQR4cm35uJrnvPHnbiml8hRDE290vp4hqs2PpNHz+b3L/KO2mZwP+YKFioT7YZrYflyCF9MzyjP6E1G/jd5xFnCe/d9Hcuo/1ZOOQ55YxaMtd1rHkSjWYIJyCzLiOMCbp3uwe7bGevTonBVApr3ajbFf6szm+0rjAKroujpjeAyM7qRDgifeViw6sit72QujjsDmlTEF5GmSGYhjFXqQbjhYROhGE1X4iVcYqRQdN/6nY9aQeN9kzaov47MBiMwJzjwZ33RL5CQT2x17Jg5L4YoEXCe5XSkK3o8EbfBld9vXSTMDsXD8fNAyE9NCistPx2WBB3Y/BW5sT6lI+SgqnPs8amw7K1NRQukrGH0pJyorX67UV51w7GsVbUbozpfmbNsXG8k4uACzv+Iua9YPooA6nRdiULfarW+nH8hB3ZuRnIZUuKV/LcybPh29772in+O9K/A==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: rabbitmq-default-user
