---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: rabbitmq-default-user
spec:
  encryptedData:
    password: AgAibAZNdg8ckR9/f3TbitJmPyuFUZ7m35D3r8Z/XLxhQtox6/Yjk0xEVoCIJaJSIl9YOmhIkMFtNujfZX4dQaHGRrlRaKnMTwkR3IC94gg4+X31ybaQokddp27OpJ7TKfwZh+8U+STEJuO1q9E3w1TFC9nXGMQam2MGUcPvxvkPf3DrHqJhZt9nmy8TjsN3lz9wEdJr3iNswWgLTx6c3Sju3p1yuGvz1qoh+F5qBjoLOLDACSu+LfSLOPqSlXYenroU9s2n0UVLDUiLp4voPVcmB6diEoh4V+bMEJC+YOOAHHgZx9yEwDYyk1KeeRt0Oy5WL0bEfmo26VeqQj4ztpcDR+8jeXgXNwEqyp56g4r7m5z0Hb1a55xPlwnisTzbgWXZ2Ta02QAVo1mfnwAwwWQXfdLmyFJkl8XhSvdlC4zYb/8kucxJl4p7oS8yvCC9YVVTpPKTetnyElKP4cXYmVtzlInDQ9FhxwEaK7pxBh8S7lFz+6MqtJ1I+U6ZCtY5h68zGI/dVjx/KlwvKNlLUrepk0A8Qxe14VJVSA/wMK5MvTGlikXHS32XC/JYsqEW3JfVUbqXBLZTrm30gURF303+FllbrgV90vXckrSMFIvMwjV/NmFCmPfMu5vkzU/0zvZFXE3EMyPwStA73nAOCXCA8aasT0MhNHyBbeAAhVH8vE6DrNrs69qFQ0C7QHq7nh0qqQ6yR3YUtZ2KxI+TMLggf699mwqvThXRBSbSsDVTgVCC1YXfTUKBe/MxwO7IEh3s6A==
    username: AgCe6O3U1CXsYxjLA+zAx/YWegztQFF6GdHg4qD1FkpsXgTbCO2W3bO2fNlV5PS98JvnL2u8G9uEFdph9Bbnxj0YHtRseSg4KPOGoFUeFfxGOep8YeaMoewK5KeEP4r91GQ+wp1Y4bWi46G7004AUP2zNKtOeiZhOvjiOD2C7BZCJNVA1GPyxSrKc5IOLQAyqBgPu7i6+vMTgFjvWLvjOsPzrxX29UMZZSZeKF8/mYjXf4ptdcr0awlNtOP3rEKsXdfmSgXZP3eaplKKk6R3ee9gg+8HLGOErAKcqbpKpYIE/1GU7EKtKtRkpxUMEIrOmRso8B6c9BYjaJV4aQYwA3gjPve+i+9xA57ZCsQle/3pK63xfcVTbUrluhFs48ekch38UsFbFHXlRPc+7sgfbcwREinqD5zWOrcMWj3i+hUE7va2oIFKNNvlVhkK1Bf7NJQvxpWcovZtae6PTQjkOiRPRoga3uAayTpWLnP47bwsmr82c/78fGv+jlc3w/dTpY9Je/V9FSs2IjctttMk2Zb4XOjLhhX9yfGQdW42S6jtJQS8ZjRnLAlTBQcvmvSZ8GNetg0gIMPzK5vS3IKGWVxeapputEkRvqSCgC3clKQoghPagX+eyhjURweUw9X6wDCYpPlAgoPKB9zfDGpV8bEEqF6ueLlPnSb+2JIQ4DgoAMI9vLpNVt+XUMsxXclisNNvNYLrlw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: rabbitmq-default-user
