---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: rabbitmq-default-user
spec:
  encryptedData:
    password: AgCZ4m8KcjvXYtUjYIfKgPIM3MHrc1uSRbDoBqtx1B3cTELAilid/Q7DBi3bZwpznR35o++tDsjn5Bd1F0D7KkKY6Cq8rXDeSKrpA4FThCTH0WrUJmku1Wj4Ck9XhEK5IZ+x5mihNwrMHMOtTN5JxIgIcdBnCXBQWQ2KW0JmU5/j0E2+RdvLPxzwj7q3gMx0KfZid3+rNNJKHnwa1xMOkSc6NZ7Lrnuxj5gx35xs+/NEZSTyHLH+zO5eEJCfj1KQqUueIaJsGMO/g5uDKy/vtTszS8vjcK+WQFSVqlu3XX4XrVVq1rl0lVo45bXVIKPzFPm0tBPUIKyxNKCQcOrgESHfMe0fUiiNe8yvX2NOLLYXae7tabwfXyxYG1jboKo9cwBd9/dJZBh+tQU5DB1qazc25bk+RobzOThx/mmzzUKtW3++adZ4fplUeqtoZYobFabPtuCp5psYAp+rVuOeOGRSn7CcU4lpqUzRWKhkyBsGvpqWfyMjnn95+o3MO/hTvk/7gKYjeeCM/Ckd+yQWG5yGK46O/KAO34bFi/feGCYIaStUNhWXfz4M94YsI6y7lLELA2PhmxF/Uy0MPUAVwSgFo/5n0OAHITrNnk2RzH3KtoTffVGmWPEEXDZEoptWdK2Ho3JjtILu5cPJ7rHP+XOkcH1r4/87lz5mFyrazw2GzohNLTAmBXDnlR3GRj+BVc6zvJ6eXcS1gCmqzNSpF/B7gdDA0Mqii2DDGmtqcSl5lpWdzumZ9+HZ86frtKpUrLGlGA==
    username: AgAlCQqduBMDcqx9s1xQmVBUiETO2IdPKEbVanPhcy/0xBjBm+A5wGj142sGi3hiPAdMsCD50VdMDLx5wBemVFHwA15sYJaJl315z7rcbZ0PcZIf24q0VyUfvP3R4PqpHIIr1Azy3IJi0xLKDqT2St5WdayWfVvmdXKoyAGvAFiokessWqcd3GSm/VNDthlIXxpf9WAewWdYWroc9Hjjd9ZO3n2E+y6DLkiz7oAKn9pQXAaKQpW53qmclnLpCAkitpC68XUp6uW6LR/C5fz4wzeI9A9sUC5RHQeILEvP+XYJ2UZRzGMri959n/f3bEsIYR/5BY7UJ/GO0vFIazu6t8YK0mEGKEwqysyo8hstZgvGLgHRDO2FVsgvtSjWXb4BbUu0gjQ7WBc3Ssfp30D6ATLYW+T9ydS7ihNxx77DKFktxYhxinV2n7/JTWB5m+AzQdru/X3TvtwNwzUAwfUX8NwnBWbaykjAowImQ7HeyOyOv5ZHb/CLs2RrINM37X7Nh7VeP9pN4Wc82mq0H2LHp6f9xqRxgn2H7oGUh4avAjUkTSQiCZTsR3+fSG+kW3d+x96hU33Fn1EEbZfdmUrTCsrH6jYUYBqsCjJrQ9dCI6rKi1zvVNIkHVfcvWZYslBN9ZvxX6rAzEbqBRuwU1T8m1Wha27i7RhtUFNx9MqEcszmUmmrGqvANaelrFtWr8pkeW4A6yxocA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: rabbitmq-default-user
