apiVersion: apps/v1
kind: Deployment
metadata:
  name: controlroom
  namespace: integration-project-2026-groep-2
  labels:
    app: controlroom
  annotations:
    argocd.argoproj.io/sync-wave: "3"  # Sync after databases and infrastructure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controlroom
  template:
    metadata:
      labels:
        rabbitmq-client: "true"
        app: controlroom
    spec:
      securityContext: {}
      containers:
        - name: controlroom
          image: ghcr.io/integration-project-2026-groep-2/controlroom:latest-dev
          env:
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: CONTROLROOM_RABBITMQ_USER
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: CONTROLROOM_RABBITMQ_PASS
            - name: RABBITMQ_VHOST
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_VHOST
            - name: RABBITMQ_URL
              value: "amqp://$(RABBITMQ_USER):$(RABBITMQ_PASS)@rabbitmq:5672/"
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: ELASTICSEARCH_URL
              value: "https://elasticsearch-es-http:9200"
            - name: CONTROLROOM_ES_USER
              valueFrom:
                secretKeyRef:
                  name: svc-controlroom-basic-auth
                  key: username
            - name: CONTROLROOM_ES_PASS
              valueFrom:
                secretKeyRef:
                  name: svc-controlroom-basic-auth
                  key: password
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: es-ca
              mountPath: /etc/ssl/certs/es-ca.crt
              subPath: tls.crt
      volumes:
        - name: es-ca
          secret:
            secretName: elasticsearch-es-http-ca-internal
            items:
              - key: tls.crt
                path: tls.crt