apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm
  namespace: integration-project-2026-groep-2
  labels:
    app: crm
  annotations:
    argocd.argoproj.io/sync-wave: "3"  # Sync after databases and infrastructure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crm
  template:
    metadata:
      labels:
        rabbitmq-client: "true"
        app: crm
    spec:
      securityContext: {}
      containers:
        - name: crm
          image: ghcr.io/integration-project-2026-groep-2/crm:latest-dev
          env:
            - name: CRM_RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: CRM_RABBITMQ_USER
            - name: CRM_RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: CRM_RABBITMQ_PASS
            - name: RABBITMQ_URL
              value: "amqp://$(CRM_RABBITMQ_USER):$(CRM_RABBITMQ_PASS)@rabbitmq:5672/"
            - name: HEARTBEAT_INTERVAL_SECONDS
              value: "1"
            - name: SYSTEM_NAME
              value: CRM
            - name: POLLING_INTERVAL_SECONDS
              value: "60"
            - name: POLLING_STATE_PATH
              value: /tmp/polling_checkpoint.json
            - name: LOG_SERVICE_NAME
              value: CRM
            - name: LOG_RABBITMQ_LEVEL
              value: INFO
            - name: SALESFORCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: crm-secret
                  key: SF_USER
            - name: SALESFORCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: crm-secret
                  key: SF_PASS
            - name: SALESFORCE_SECURITY_TOKEN
              valueFrom:
                secretKeyRef:
                  name: crm-secret
                  key: SF_TOKEN
            - name: SALESFORCE_DOMAIN
              value: login
            - name: LOG_LEVEL
              value: INFO
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"