apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: integration-project-2026-groep-2
  labels:
    app: kibana
spec:
  type: ClusterIP
  selector:
    app: kibana
  ports:
    - name: http
      port: 5601
      targetPort: 5601
